### ISSUE TITLE
No map shown when using Umlaut in alias

### ISSUE THREAD

**Issue by BertramVielsack** [JasonRivers/Docker-Nagios#152]
Hi,
after upgrade to jasonrivers/nagios:4.4.14 the ui no longer shows the "Map" while "Legacy" still worked.

This seems to be caused by using German umlauts within aliases.

The issue can be reproduced with the following files:

docker-compose.yml
```
services:
  nagios:
    image: jasonrivers/nagios:4.4.14
    ports: 
      - 80:80
    volumes:
      - ./localhost.cfg:/opt/nagios/etc/objects/localhost.cfg
```

localhost.cfg:
```
define host {
        use                     linux-server
        host_name               localhost
        alias                   localhost Büro
        address                 127.0.0.1
        }

define service {
        use                             local-service,graphed-service
        host_name                       localhost
        service_description             PING
	check_command			check_ping!100.0,20%!500.0,60%
        }
```

When I remove "Büro" from alias or use version 4.4.8 the issue does not occur.

Regards
Bertram
