### ISSUE TITLE
Timezone/Servername ENVs do not work

### ISSUE THREAD

**Issue by tonyjafar** [JasonRivers/Docker-Nagios#77]
docker-compose:
```
---
version: '3'
services:
  nagios:
    image: jasonrivers/nagios:latest
    ports:
    - "8080:80"
    environment:
    - NAGIOS_FQDN=nagios.test.com
    - NAGIOS_TIMEZONE=CEST
    volumes:
    - /opt/nagios/etc/:/opt/nagios/etc/
    - /opt/nagios/var:/opt/nagios/var/
    - /opt/Custom-Nagios-Plugins/:/opt/Custom-Nagios-Plugins/
    - /opt/nagiosgraph/var/:/opt/nagiosgraph/var/
    - /opt/nagiosgraph/etc/:/opt/nagiosgraph/etc/
```
after running docker both ENVs "timezone and servername" still the same in orginal Container.
check in container : 
```
 cat /etc/apache2/conf-available/timezone.conf
PassEnv TZ
cat /etc/apache2/conf-enabled/servername.conf
nagios.example.com
 ```
the timezone in Nagios Web still also in UTC
I had to fix that in Dockerfile like this:
```
FROM jasonrivers/nagios:latest
RUN rm /etc/localtime && ln -s /usr/share/zoneinfo/Europe/Berlin /etc/localtime
COPY servername.conf /etc/apache2/conf-available/servername.conf
COPY timezone.conf /etc/apache2/conf-available/timezone.conf
```
File timezone.conf
```
SetEnv TZ "Eourpe/Berlin"
```

File servername.conf
```
nagios.test.com
```
