### ISSUE TITLE
Warning: This plugin must be either run as root or setuid root.

### ISSUE THREAD

**Issue by saytik** [JasonRivers/Docker-Nagios#82]
After  restarting container. all hosts are DOWN. 
Warning: This plugin must be either run as root or setuid root.

ls -la /opt/nagios/libexec/check_icmp 
-rwsr-xr-x 1 nagios nagios 271424 Oct 16 08:52 /opt/nagios/libexec/check_icmp

Then i run 
chmod u+s  /opt/nagios/libexec/check_icmp 

But when i restart container all hosts are DOWN.  The problem is exist when i have upgraded  container to 4.4.2

my docker-compose (using nagios:latest):

```
services:
  nagios:
    network_mode: "bridge"
    extends:
      file: docker-compose.yml
      service: nagios 
    container_name: nagios 
    environment:
      VIRTUAL_HOST: my.domain.com
      MAIL_RELAY_HOST: ${MAIL_RELAY_IP}
      NAGIOS_FQDN: my.domain.com
      NAGIOS_TIMEZONE: Europe/Kiev 
    volumes:
      - /data/nagios/etc/:/opt/nagios/etc/
      - /data/nagios/var:/opt/nagios/var/
      - /data/nagios/custom-plugins:/opt/Custom-Nagios-Plugins
      - /data/nagios/nagiosgraph-var:/opt/nagiosgraph/var \
      - /data/nagios/nagiosgraph-etc:/opt/nagiosgraph/etc \
```
