### ISSUE TITLE
Issue folders

### ISSUE THREAD

**Issue by kanenses** [JasonRivers/Docker-Nagios#92]
Hi,

every time I uncomment, eg, #cfg_dir=/opt/nagios/etc/servers, and add my cfg here, nagios pid stop working.

Any help please? :-)

**Comment by kanenses** [comment]
Add, I have deploy a new test VM, add getting:
> Error: Could not open CGI config file '/opt/nagios/etc/cgi.cfg' for reading!

Deploy using docker compose and traefik.

```
  nagios:
    container_name: nagios
    image: jasonrivers/nagios:latest
    restart: always
    networks:
      - web
    environment:
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/nagios/etc:/opt/nagios/etc
      - ${USERDIR}/nagios/var:/opt/nagios/var
      - ${USERDIR}/nagios/plugins:/opt/Custom-Nagios-Plugins
      - ${USERDIR}/nagios/nagiosgraph-etc:/opt/nagiosgraph/var
      - ${USERDIR}/nagios/nagiosgraph-var:/opt/nagiosgraph/etc
      - ${USERDIR}/nagios/etc/hosts:/opt/nagios/etc/hosts
    labels:
      - "traefik.enable=true"
      - "traefik.backend=nagios"
      - "traefik.frontend.rule=PathPrefixStrip: /nagios"
      - "traefik.port=80"
      - "traefik.docker.network=web"
      - "traefik.frontend.headers.SSLRedirect=true"
```
